name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: npm install 
        run: npm install

      - name: lint
        run: npm run eslint

      - name: build
        run: npm run build

      - name: test
        run: npm run test

      - name: e2e tests
        uses: cypress-io/github-action@v2
        timeout-minutes: 10
        with:
          start: npm run start-prod

      - uses: akhileshns/heroku-deploy@v3.12.12        
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "tranjt-pokedex"
          heroku_email: "randfresh911@gmail.com"
          healthcheck: "https://tranjt-pokedex.herokuapp.com/health"
          checkstring: "ok"
          rollbackonhealthcheckfailed: true
          
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.33.0
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
      
      - name: Notification success
        if: ${{ success() }}
        uses: 8398a7/action-slack@v3        
        with:
          status: custom
          fields: commit,author,took
          custom_payload: |
            {
              color: 'good',
              attachments: [{               
                text: `A new version deployed to https://tranjt-pokedex.herokuapp.com/ (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
       
      - name: Notification failure
        if: ${{ failure() }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      